settings:
  # whether bot is deployed in production mode
  production: 1
database:
  name: ranked_choice_voting
  user: rcv_user
  password: YOUR_DATABASE_PASSWORD
  host: localhost
telegram:
  bot_token: YOUR_BOT_TOKEN
  webhook_url: YOUR_WEBHOOK_URL
  sudo_id: YOUR_SUDO_ID
webapp:
  cors_origins:
    - https://rcvdev.milselarch.com
    - https://server.milselarch.com
    - https://ranked-choice-bot.web.app
    - http://localhost:5001
